### ISSUE TITLE
network monitor displays double actual speed

### ISSUE THREAD

**Issue by nokel** [rainmeter/rainmeter#149]
I've only recently noticed that this is happening and it's quite annoying, could someone let me know how to fix this? disabling anything in network connections just flat out kills my internet so there's no option for that unfortunately otherwise I would have.

**Comment by PreownedFIN** [comment]
I have noticed similar behaviour.
It may have something to do with the update speed of the meter. If I have set the updates to happen every 1000ms, the updates don't actually happen once a second. The time between updates varies anywhere from 1 second to 5 seconds, and whenever an update takes longer, the network speed spikes to unrealistic numbers. (I alegedly have downloaded at >300MB/s over a 1Gbps connection).

I think it takes all of the traffic between updates (can be as long as 5 seconds) and when the update happens, it shows the traffic from the last 5 seconds as traffic that happened in the last second.
I think this is because **Rainmeter doesn't actually measure network speed, only the amount of data between updates**, and relies on the updates actually happening at 1000ms intervals.

_The actual problem is that Rainmeter doesn't update at the intervals it is given._

**Comment by brianferguson** [comment]
> ... and relies on the updates actually happening at 1000ms intervals.
>
> _The actual problem is that Rainmeter doesn't update at the intervals it is given._

During the start of the [update cycle](https://docs.rainmeter.net/manual/skins/#Update) for each skin, Rainmeter will enumerate and cache the state of all the logical and physical network interfaces on the system. This is done so that each measure in the skin has access to the same values. This cache is not modified by Rainmeter and is a direct copy from what Windows reports. When [Net](https://docs.rainmeter.net/manual/measures/net/) measures go through the update, they read directly from the cached value instead of "polling" Windows for the information.

The above happens during every update cycle for each skin, but measures (and the meters that they are bound to) can utilize [UpdateDivider](https://docs.rainmeter.net/manual/measures/general-options/#UpdateDivider) to essentially "skip" some updates. If using an UpdateDivider on the measure in question **and/or** on the meter using the measure...then it can appear as if it takes extra long to update.

It is important to remember Rainmeter or Windows measures **all** traffic in and out of the NIC of the computer. This means that it can also be measuring any traffic between the system and other devices on the network including routers, other computers, phones, and any other devices on the network.

It is also important to realize that the values reported to Rainmeter from Windows is just a "snapshot in time" and may not be in sync with other methods of measuring network data (like the Task Manager).

Rainmeter does not "double" any results it gets from Windows, nor does it update at any other interval that what is defined in the skin. [[Source](https://github.com/rainmeter/rainmeter/blob/master/Library/MeasureNet.cpp)]

I am marking this issue as closed. If more help is required, please post on the help forums: [https://forum.rainmeter.net/viewforum.php?f=10](https://forum.rainmeter.net/viewforum.php?f=10)

-Brian
