### ISSUE TITLE
Work on Publishing to Windows store... if at all possible, that is. 

### ISSUE THREAD

**Issue by Dr-Chronosphere** [rainmeter/rainmeter#153]
They seem to have made the process fairly simple with tools available [here](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter).
After doing that, I guess [this](https://developer.microsoft.com/en-us/windows/projects/campaigns/desktop-bridge) is necessary. In a nutshell, I just think that the Windows Store is in great need of high-quality apps and think that the more open-source projects post their apps to the Windows Store, the better it can be for all of the community. After all, one of the benefits of such an endeavor would be an automatic update system to take care of rainmeter updates, which would be a great feature. If it is an app that isn't allowed in the Windows Store, then I think that rainmeter should adopt the squirrel updater for automatic program updates.

**Comment by Axinoe** [comment]
I don't think this should be done. Rainmeter would probably be too user-based to be put on the Windows store, along with other issues that could come along

**Comment by Dr-Chronosphere** [comment]
I'm not very well-versed in the dev world, so could you explain what you mean?

**Comment by Dr-Chronosphere** [comment]
Shouldn't an automatic update system be addressed, though? The squirrel updater is what electron apps use and it is a completely seamless process.

**Comment by brianferguson** [comment]
We are hesitant to move into the Windows Store since they are pushing UWP and PWA apps versus win32 apps like Rainmeter. Personally, I think they are allowing win32 apps in via desktop bridge in an attempt to bolster the number of apps in the Store (but that is my opinion). Rainmeter can never be a UWP or PWA app, so publishing there is not a high priority for us. We have talked about a better update delivery method, but it really hasn't gotten out of the "discussion" phase. Honestly, we prefer to be "in control" of the update process, and like reminding people to visit rainmeter.net for updates and information about new features.

-Brian
