### ISSUE TITLE
UTF-8 support in .ini files (suggestion)

### ISSUE THREAD

**Issue by ljoonal** [rainmeter/rainmeter#168]
UTF-8 is and has been the standard for text for a while now. Adding support for it would be good, even if that wasn't the default.

**Comment by raiguard** [comment]
Despite the (very) vocal opposition from the Rainmeter devs, I use UTF-8 in my skins without issues. I would use UTF-16 LE if GitHub supported it (it won't show commit changes for UTF-16 LE files) though.

**Comment by ljoonal** [comment]
Using UTF-8 'works', but the point of it would be to support special characters. Things like ° didn't work for me when trying to use UTF-8, and it was a struggle to find what my text editor (VSCode) called the encoding that worked. And things like UTF-8 emoji will most likely never work without support for them (?).

**Comment by raiguard** [comment]
For the degree symbol specifically, I found the Unicode reference to it in the font I used (Roboto) and used a character reference variable. That seems to be a viable workaround.

**Comment by brianferguson** [comment]
> UTF-8 is and has been the standard for text for a while now. Adding support for it would be good, even if that wasn't the default.

I am not sure what "standard" you are referring to as there is no "standard" encoding for text. Here are some common encodings: [Common character encodings](https://en.wikipedia.org/wiki/Character_encoding#Common_character_encodings)

Rainmeter relies heavily on the WinAPI to measure system data and to read/write data to files. Windows has used UTF-16 (little endian) internally in memory to represent text for several decades and their API provides easy access for UTF-16 encoded text. This is the main reason we recommend using it. The functions we use will work for ANSI encoded text as well (which is why some UTF-8 encoded text works).

While UTF-8 is popular in a lot of cases, any decent text editor (even notepad) can save text as UTF-16. This doesn't mean we won't add support for it someday, but it isn't a very high priority for us at this time.

-Brian
