### ISSUE TITLE
DesktopWorkArea fullscreen/Windows taskbar resize bug.

### ISSUE THREAD

**Issue by grappas** [rainmeter/rainmeter#192]
I'm using rainmeter apps on secondary display (as system monitor, etc.) [like this](https://i.imgur.com/2J2aGma.png). Each time applications on primary/main monitor goes exclusive fullscreen (even in native resolution) DesktopWorkArea disables itself and windows are covering my rainmeter apps. Same for even momentary, slight change in desktop layout such as taskbar resize. I have to manually hit "refresh" to get DesktopWorkArea to work again.

After second thought: I don't know why DesktopWorkArea is not accessible through "Manage" page. It's pretty useful and deserves more attention than that.

**Comment by raiguard** [comment]
Just curious, are you using ModernGadgets' new sidebar functionality, or did you edit the work area yourself?

**Comment by grappas** [comment]
Ummm... edited myself. Is it such option in ModernGadgets? Didn't knew.

**Comment by grappas** [comment]
Yep. That works. But that's you guys should've repaired ;)

**Comment by raiguard** [comment]
Well you will still encounter the same issue as before. I am working on a way to automatically work around it, but haven't finished it up yet. It would be interesting to know if something could be done on the Rainmeter side so I didn't have to implement the workaround.

**Comment by grappas** [comment]
Still getting same bug after taskbar resize/changing screen resolution, but on application fullscreen problem is solved so far by ModernGadgets.

**Comment by brianferguson** [comment]
This isn't really a bug, but more of a OS design "feature". Since Windows allows any program to modify the system work area (including when the taskbar location or size changes), it's impossible to know when a change to the work area is supposed to be permanent or just temporary.

So basically, there is no way to know if the work area should be reset back to what is defined in Rainmeter.ini when Rainmeter detects a change in the work area since there are many valid reasons other programs might need to change the work area.

That being said, we have discussed adding a DesktopWorkArea option to the Manage dialog in the past, but could not agree on the UX design for it. Maybe just a simple edit box with comma separated values is all that is needed. We would probably need a "Re-apply DWA" button as well - but we cannot do any automatic resetting of the work area when it was changed. Any ideas on the UX design are welcome. 😀 

-Brian

PS - We really don't recommend trying to automatically change Rainmeter.ini values directly through skins since those values should only be edited (either manually or via Manage) by the end user themselves (although for this particular feature doesn't have an "easy" to edit it). Too many skins automatically write to Rainmeter.ini and decide on settings the user should have (not saying you are doing that). There are timing issues when the file might need to be writable by Rainmeter but is blocked because another action is writing to it.

**Comment by grappas** [comment]
NOTE (00:51:03.566) : System: Work area changed

If desktopworkarea enabled && work area changed
then
Sleep 5000
Refresh rainmeter

**Comment by brianferguson** [comment]
Again, we will not be changing it automatically since there are valid reasons for another program (or Windows itself) to change the work area.

We are open to some new items in the Manage dialog that will set and reset the work area.

-Brian

**Comment by grappas** [comment]
I'm not saying about changing It. Just resefreshing on work area changed (workaround a problem). It wouldn't be a problem in Beta even as a command in Rainmeter.ini (DesktopWorkAreaAutoRefresh=1)

**Comment by superuser7777** [comment]
```
If [desktopworkarea enabled] && [work area changed]
then
Sleep 5000
Refresh rainmeter
```
Is this an idea?
Is the function to execute the process based on the log implemented?
I have searched and found no information.
