### ISSUE TITLE
rainmeter for deepin or linux software

### ISSUE THREAD

**Issue by CaoYunzhou** [rainmeter/rainmeter#198]
Can you provides suport deepin or linux software for rainmeter

**Comment by brianferguson** [comment]
Unfortunately, a complete rewrite of the entire codebase would need to happen for Rainmeter to run on any system other than Windows. Rainmeter relies heavily on the Windows API (winapi) and D2D graphics engine to function.

-Brian

**Comment by mintuser4444** [comment]
didn't function in wine.  tried to run winemaker and build with headers from mingw.  had to add -DUNICODE to the CXXEXTRAS then ran into internal mingw header problems.  i don't really know anything about windows or wine and my environment is probably broken.  someone on the internet once said rainmeter works in wine on linux 
* winelib is a good option because winelib will never change its api
* qt is a good option because it runs on anything
* replacing d2d calls with whatever and reimplementing all the MeasureCPU.cpp stuff are story point tasks
* but i haven't found how rainmeter draws those undecorated windows or how to do that on mac or linux.
* as I see it the tasks are
** determine how to draw to an undecorated window.  this may guide winelib vs qt vs whatever
** get Application.cpp out of the way
** reimplement enough of Canvas.cpp
** feed fake data from Linux/MeasureCPU.cpp
** get illustro cpu to work
** implement enough of Linux/Measure*
** find a macos programmer to take care of Macos/Measure*
** moderngadgets calls out to like hwinfo or something for the gpu meter.  hwinfo is also available on linux
anyway here are the windows things that might need to be reimplemented in the common directory.  most of the time rainmeter uses c++ namespaces but windows doesn't, but some of these may be rainmeter functions
Application.cpp
#define _CRTDBG_MAP_ALLOC
EXTERN_C IMAGE_DOS_HEADER __ImageBase;
GetCommandLine()
_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
SetErrorMode(oldMode | SEM_FAILCRITICALERRORS);
FindResource(instance, MAKEINTRESOURCE(1), RT_ICON)
LoadLibrary(L"Rainmeter.dll")
GetProcAddress(rmDll, MAKEINTRESOURCEA(1));
GetLastError());
MessageBox(nullptr, message, L"Rainmeter"
RegOpenKeyEx
RegQueryValueEx
SetCurrentDirectory
ShellExecute
RegCloseKey

CharacterEntityRef.cpp clean

ControlTemplate.cpp
MapDialogRect
CreateWindowEx
SendMessage

Dialog.cpp
ShowWindow
SetForegroundWindow
CreateDialogIndirectParam
DialogBoxIndirectParam
GetWindowLongPtr
HandleMessage
SystemParametersInfo
CreateFontIndirect
DestroyWindow
DeleteObject
Show
IsDialogMessage
SetWindowSubclass
DefSubclassProc
RemoveWindowSubclass
EnableThemeDialogTexture
EnableWindow
BringWindowToTop

FileUtil.cpp clean

MathParser.cpp clean

MenuTemplate.cpp
CreateSubMenu
CreatePopupMenu

NetworkUtil.cpp
DisposeInterfaceTable
GetIfTable2
GetBestInterface
FreeMibTable

PathUtil.cpp
SHGetFolderPath
ExpandEnvironmentStrings

Platform.cpp
RegOpenKeyEx
RegQueryValueEx
GetProcAddress
GetModuleHandle
IsWindowsServer
GetPlatformReleaseID
RegCloseKey
Is64BitWindows
GetUserDefaultUILanguage
isWow64Process
GetCurrentProcess

StringUtil.cpp
WideCharToMultiByte
MultiByteToWideChar

**Comment by deathcrafter** [comment]
Rainmeter skins are pop up Windows. Which are basically the windows you see in context menus. So they don't have any decorations.

The next problem you would face is the usage of D2D. I think wine doesn't support it. Or it may need some additional dependencies. 

About measures, they are completely based off of MS Windows libraries. So you can only barely expect them to run with wine. Tho I haven't used wine much, I can say that it doesn't provide complete windows app support.

P.S. I am planning on trying to port RM to Linux, which may turn out to be unfruitful, but it's a thing worth trying. The main problem which I will face probably will be the vast amount of distros and desktop environments.

**Comment by ikkqqstudio** [comment]
> didn't function in wine. tried to run winemaker and build with headers from mingw. had to add -DUNICODE to the CXXEXTRAS then ran into internal mingw header problems. i don't really know anything about windows or wine and my environment is probably broken. someone on the internet once said rainmeter works in wine on linux
> 
>     * winelib is a good option because winelib will never change its api
> 
>     * qt is a good option because it runs on anything
> 
>     * replacing d2d calls with whatever and reimplementing all the MeasureCPU.cpp stuff are story point tasks
> 
>     * but i haven't found how rainmeter draws those undecorated windows or how to do that on mac or linux.
> 
>     * as I see it the tasks are
>       ** determine how to draw to an undecorated window.  this may guide winelib vs qt vs whatever
>       ** get Application.cpp out of the way
>       ** reimplement enough of Canvas.cpp
>       ** feed fake data from Linux/MeasureCPU.cpp
>       ** get illustro cpu to work
>       ** implement enough of Linux/Measure*
>       ** find a macos programmer to take care of Macos/Measure*
>       ** moderngadgets calls out to like hwinfo or something for the gpu meter.  hwinfo is also available on linux
>       anyway here are the windows things that might need to be reimplemented in the common directory.  most of the time rainmeter uses c++ namespaces but windows doesn't, but some of these may be rainmeter functions
>       Application.cpp
>       #define _CRTDBG_MAP_ALLOC
>       EXTERN_C IMAGE_DOS_HEADER __ImageBase;
>       GetCommandLine()
>       _CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
>       SetErrorMode(oldMode | SEM_FAILCRITICALERRORS);
>       FindResource(instance, MAKEINTRESOURCE(1), RT_ICON)
>       LoadLibrary(L"Rainmeter.dll")
>       GetProcAddress(rmDll, MAKEINTRESOURCEA(1));
>       GetLastError());
>       MessageBox(nullptr, message, L"Rainmeter"
>       RegOpenKeyEx
>       RegQueryValueEx
>       SetCurrentDirectory
>       ShellExecute
>       RegCloseKey
> 
> 
> CharacterEntityRef.cpp clean
> 
> ControlTemplate.cpp MapDialogRect CreateWindowEx SendMessage
> 
> Dialog.cpp ShowWindow SetForegroundWindow CreateDialogIndirectParam DialogBoxIndirectParam GetWindowLongPtr HandleMessage SystemParametersInfo CreateFontIndirect DestroyWindow DeleteObject Show IsDialogMessage SetWindowSubclass DefSubclassProc RemoveWindowSubclass EnableThemeDialogTexture EnableWindow BringWindowToTop
> 
> FileUtil.cpp clean
> 
> MathParser.cpp clean
> 
> MenuTemplate.cpp CreateSubMenu CreatePopupMenu
> 
> NetworkUtil.cpp DisposeInterfaceTable GetIfTable2 GetBestInterface FreeMibTable
> 
> PathUtil.cpp SHGetFolderPath ExpandEnvironmentStrings
> 
> Platform.cpp RegOpenKeyEx RegQueryValueEx GetProcAddress GetModuleHandle IsWindowsServer GetPlatformReleaseID RegCloseKey Is64BitWindows GetUserDefaultUILanguage isWow64Process GetCurrentProcess
> 
> StringUtil.cpp WideCharToMultiByte MultiByteToWideChar

What about bottles?

https://www.usebottles.com/

**Comment by ikkqqstudio** [comment]
> Unfortunately, a complete rewrite of the entire codebase would need to happen for Rainmeter to run on any system other than Windows. Rainmeter relies heavily on the Windows API (winapi) and D2D graphics engine to function.
> 
> -Brian

But in 2025, Linux is rising, and people (probably) needed it
