### ISSUE TITLE
What's "Rainmeter.exe" on %AppData%\Rainmeter

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#221]
Hello,
I find a hidden EXE file named "Rainmeter.exe" on %AppData%\Rainmeter.
What's it?
All executable files should put on the app folder. (Program Files)
![image](https://user-images.githubusercontent.com/23485114/75552699-1be18400-5a4c-11ea-88e1-318bf822bd06.png)

**Comment by raiguard** [comment]
Rainmeter doesn't put anything in program files, it all goes in AppData. There's nothing "hidden" about that EXE file, that's just the program.

**Comment by facelesspanda** [comment]
appdata itself is "hidden", technically, though. (doesn't appear in file browser by default)

**Comment by xmha97** [comment]
After deleting file and re-creating file!
![Rainmeter](https://user-images.githubusercontent.com/23485114/75574967-7d1d4d80-5a74-11ea-965c-d691d2917eeb.gif)

**Comment by brianferguson** [comment]
Explained here:
[https://forum.rainmeter.net/viewtopic.php?f=4&t=33707#p166765](https://forum.rainmeter.net/viewtopic.php?f=4&t=33707#p166765)

-Brian

**Comment by xmha97** [comment]
> 
> 
> Explained here:
> https://forum.rainmeter.net/viewtopic.php?f=4&t=33707#p166765
> 
> -Brian

Why this executable file is not stored on `Program Files` folder?

**Comment by brianferguson** [comment]
Did you read the link?

-Brian

**Comment by xmha97** [comment]
Ok, Thank you.
Now I understood about Rainmeter.exe in the Appdata folder.
But it would be better if you change the program default installation path. (like electron apps)
![image](https://user-images.githubusercontent.com/23485114/75577395-25341600-5a77-11ea-8d2f-164fde3f0d8e.png)

**Comment by raiguard** [comment]
Huh, that's interesting. I somehow overlooked the fact that Rainmeter stores anything in program files. I'm not known for my powers of observation.

**Comment by brianferguson** [comment]
> But it would be better if you change the program default installation path. (like electron apps)

The default program installation path should be in `Program Files`. Windows "protects" this folder from malware writing/overwriting to it. `AppData` is the place to store user data, like settings.

---

Back in the Windows XP days (before Windows had protected folders), Rainmeter created a `Addons` folder which users could place their 3rd party programs. A lot of these 3rd party addons used to assume that the main Rainmeter.exe process was located in the parent folder of the Addons folder.

So the paths **used** to look like this:
|Object       | Path                                     |
|-------------|------------------------------------------|
|Main folder  |`C:\Program Files\Rainmeter\`             |
|Addon folder |`C:\Program Files\Rainmeter\Addons\`      |
|Main process |`C:\Program Files\Rainmeter\Rainmeter.exe`|
|User settings|`C:\Program Files\Rainmeter\Rainmeter.ini`|

So, when a addon program would try to communicate with the Rainmeter process, they would send the command to "..\Rainmeter.exe". This worked fine during the XP years.

Later, Microsoft no longer recommended "writing" anything to the `Program Files` folder after installation. This meant our skin installer could no longer write to this folder - meaning any addons within a rmskin file could no longer install correctly. This also affected our settings file `Rainmeter.ini` file. All these "writable" files needed to be stored in the `AppData` folder, but this meant that a lot of addons could no longer take advantage of the main Rainmeter.exe process being in the parent folder of the Addons folder. This is why the "stub" executable was introduced. This "stub" Rainmeter.exe program essentially passes any arguments to the main Rainmeter.exe process so that older addons still work correctly.

This changed the paths to this:
|Object       | Path                                          |
|-------------|-----------------------------------------------|
|Main folder  |`C:\Program Files\Rainmeter\`                  |
|Main process |`C:\Program Files\Rainmeter\Rainmeter.exe`     |
|Addon folder |`C:\%AppData%\Rainmeter\Addons\`               |
|Stub program |`C:\%AppData%\Rainmeter\Rainmeter.exe` (Hidden)|
|User settings|`C:\%AppData%\Rainmeter\Rainmeter.ini`         |

---

I hope this helps a little bit more.

-Brian

**Comment by xmha97** [comment]
Why don't you use a junction link or symbolic link (aka symlinks) instead of AppData EXE?
Like `%LocalAppData%\Microsoft\WindowsApps\`
![image](https://user-images.githubusercontent.com/23485114/84572654-d6558680-adb0-11ea-8b82-1b7360266c88.png)

**Comment by brianferguson** [comment]
Those can be changed/deleted at any time by the end user, and if changed would make some addons not function correctly. The stub exe works fine.

-Brian

PS - Please don't create duplicate issues.

**Comment by paul1126** [comment]
https://www.rainmeter.net
this site explains
i recommend do not deleting that file
