### ISSUE TITLE
Dividing dotted numbers incorrectly

### ISSUE THREAD

**Issue by volkansari** [rainmeter/rainmeter#222]
Gumus=103.84340
[MeasureGumus]
Measure=Calc
Formula=(Gumus=0?0:[Gumus:/31.1034768]) divinding wrong
DynamicVariables=1

MeasureGumus=3,35163*31,1034768=104.24742--- multiplication is wrong.
Real Value=        103.84340----the value that should come out

**Comment by brianferguson** [comment]
The divisor must be an integer.
[https://docs.rainmeter.net/manual/variables/section-variables/#Scale](https://docs.rainmeter.net/manual/variables/section-variables/#Scale)

Basically, the scale is truncating the divisor to `31`. Instead of using the scale parameter to a section variable, just use regular division. See below.

``` ini
[Gumus]
Measure=Calc
Formula=103.84340

[MeasureGumus]
Measure=Calc
Formula=(Gumus=0?0:[Gumus:/31.1034768])
DynamicVariables=1

[MeasureGumus2]
Measure=Calc
Formula=(Gumus=0?0:(Gumus/31.1034768))

; Check MeasureGumus
[Check]
Measure=Calc
Formula=(MeasureGumus * 31.1034768)

; Check MeasureGumus2
[Check2]
Measure=Calc
Formula=(MeasureGumus2 * 31.1034768)
```

We added a note in the documentation about the divisor.

-Brian

**Comment by volkansari** [comment]
Thank you Brian  you right
