### ISSUE TITLE
Rainmeter forcing system tray icons to open on start up

### ISSUE THREAD

**Issue by pkaka1** [rainmeter/rainmeter#288]
I am having this weird issue. I am using rainmeter app (v 4.5.6) . When i wake up the computer from sleep or shut down the system trays icon open(expand) automatically in left corner. It is really annoying. 
 Currently not using any skin. Is there a fix for this?
![Untitled](https://user-images.githubusercontent.com/95593462/144767593-68cd8683-c539-4a25-996f-84e7e888e124.png)

**Comment by deathcrafter** [comment]
So it doesn't happen when not using Rainmeter?

**Comment by pkaka1** [comment]
Yes. Seems like skin specific. Once I load drop top four, it happens. (when i unload it still happens and I have to remove rainmeter again).

**Comment by brianferguson** [comment]
No need for multiple bug reports.
https://forum.rainmeter.net/viewtopic.php?t=39156#p201276

Also, nothing in the main Rainmeter executable is causing this. Obviously, the skin "drop top four" is most likely the main cause, as you alluded to already. It would be best to contact the skin author about this, or wait for some help on the forums.

I am fairly certain that the skin is opening up this panel directly, instead of letting the user do it.

-Brian
