### ISSUE TITLE
I can't get Asuramaru Bundle v 1.0.5 to uninstall.

### ISSUE THREAD

**Issue by Contrabardus** [rainmeter/rainmeter#297]
I'm running Windows 11 on the latest stable version of Rainmeter from the official page as of the date this is posted.

It installs and runs fine, but I decided to go with another skin that provides more detail about some of the monitoring and now I can't get rid of Asuramaru Bundle.

Every time I open windows it launches, and I can't get it to stop doing that.

I've used the "uninstall" in settings several times and it just clears off the elements of Asuramaru from my screen, but it still runs in the system tray and does not uninstall anything.

If I go into the documents/skins folder and remove it from there, it still attempts to launch every time I restart my PC and I get an error message about how it can't launch and the icon still ends up in the system tray.

It seems my only recourse is uninstalling Rainmeter entirely, so this should probably be fixed.

**Comment by brianferguson** [comment]
I have no idea what "Asuramaru Bundle" is, nor where to download it. A quick google search turned up nothing.


> I've used the "uninstall" in settings several times and it just clears off the elements of Asuramaru from my screen, but it still runs in the system tray and does not uninstall anything.

What "uninstall" in settings? There is no option to uninstall a skin in the Rainmeter settings tab. If you are talking about "uninstalling Rainmeter" from Windows settings app, then are you suggesting that Rainmeter failed to uninstall?  If so, you could try a clean uninstall.
[https://docs.rainmeter.net/tips/clean-rainmeter-uninstall/](https://docs.rainmeter.net/tips/clean-rainmeter-uninstall/)


> If I go into the documents/skins folder and remove it from there, it still attempts to launch every time I restart my PC and I get an error message about how it can't launch and the icon still ends up in the system tray.

Again, do you mean Rainmeter still launches and shows the Rainmeter tray icon? Because deleting a skin does not mean Rainmeter won't show the Rainmeter tray icon. Or are you talking about another icon for this "Asuramau Bundle" ? Also, what is the error message?

It's basically impossible to help since I have no idea what skin you have downloaded, nor what the error message even is. If you could provide a link to the skin, and some screenshots of the error message, that would help us to resolve your issue.

-Brian
