### ISSUE TITLE
Why Initialize() function return number value for Strings?

### ISSUE THREAD

**Issue by MASTREX** [rainmeter/rainmeter#308]
I am creating a simple file reading skin and in it I was calling ReadFile function through Initialize() to load the file content on start but it always return '0'
After  lot of trial and error, I was able to reach to conclusion that Initialize function return number value for Strings

>My Test skin files:

test.ini
```ini
[Rainmeter]
Update=-1
AccurateText=1

[Metadata]
Name=Test
Author=
Information=
Version=
License=Creative Commons Attribution - Non - Commercial - Share Alike 3.0

[Variables]

[MeasureScript]
Measure=Script
ScriptFile=#@#code.lua

[MeterString]
Meter=String
MeasureName=MeasureScript
FontSize=16
FontColor=255,255,255,255

```

Case 1:
@Resource/code.lua (with initialize function)
```lua
function Initialize()
	MyVariable = 'Hello, world!'
	return MyVariable
end
```

Result:
![image](https://user-images.githubusercontent.com/38161604/185678400-8ebb24d2-822b-4fc8-ba94-9ced4132eada.png)

Case 2:
@Resource/code.lua (with update function)
```lua
function Update()
	MyVariable = 'Hello, world!'
	return MyVariable
end
```

Result:
![image](https://user-images.githubusercontent.com/38161604/185678702-a9e2c203-9f9d-46fc-81e0-c463b55a272c.png)

**Comment by deathcrafter** [comment]
It's not Intialize whose return value is used when resolving the measure name, it's the Update function. It's not an error, it's how things work.

**Comment by brianferguson** [comment]
The `Initialize` function is called only when the skin is activated or refreshed. It's purpose is to process any code that the script needs "set up" in order to function properly. Like setting up global variables, etc.
[https://docs.rainmeter.net/manual/lua-scripting/#Initialize](https://docs.rainmeter.net/manual/lua-scripting/#Initialize)

Any value returned from `Initialize` is ignored.

**The returned value from the `Update` function is what Rainmeter retrieves during the update of the measure.**

So, in this case, you could simply omit the `Initialize` function altogether since it's redundant. Or you could do something like this:
```lua
function Initialize()
  MyVariable = 'Hello, World'
end

function Update()
  return MyVariable
end
```
`MyVariable` will be a global variable.

-Brian

**Comment by MASTREX** [comment]
Any value returned from `Initialize` is ignored.

This is not mentioned in docs. I have to update only once so I thought to return file content from Initialize function.

Thanks for clarification 😊
