### ISSUE TITLE
Issues regarding new Update in script measure

### ISSUE THREAD

**Issue by deathcrafter** [rainmeter/rainmeter#314]
## Issues
1. `return '99', 'Ninety-Nine'`
 - **Expected**: 99 as number, Ninety-Nine as string
 - **Result**: 99 as both number and string
2. `return 99, 98`
 - **Expected**: 99 as number, 98 as string
 - **Result**: 98 as number and string
3. `return [nil[, nil]]`
 - **Expected**: 0 as number, empty string (even [docs](https://docs.rainmeter.net/manual/lua-scripting/#Update) state this, but it didn't really work this way)
 - **Result**:   0 as number and string

## Suggestions
1. `return true[, false]`
 - **Expected**: 1 as number and 0 as string
 - **Result**: 0 as number and string

**Comment by brianferguson** [comment]
Issue 1: Those are both strings, so the first one will win.
Issue 2: Those are both numbers, so the first one will win.
Issue 3: The docs might need tweaking, but 0 is the correct return value for both string and number values.

The return "order" does not matter, it is all about "type". It only looks at 2 possible returns. So if it finds a string, it sets the "string value" (and the "number value" IF the number has not been set yet). Then if it finds a number, that is set to the "number value" (regardless of if the "string value" has been set or not).

About the boolean type. I didn't account for that since we have never supported `true` or `false` as a return type for the Update function. My original idea had this working, but I was thinking along the lines of the custom function parsing. We can revisit this, but I really don't think it's needed.

-Brian

**Comment by deathcrafter** [comment]
Fair enough 👍
