### ISSUE TITLE
GPU Meter Won't Refresh 

### ISSUE THREAD

**Issue by Alex-Mirov** [rainmeter/rainmeter#323]
Hello

When using with rainmeter 4.5.16 on windows 11, the "GPU Meter" won't auto refresh after restart or logoff and
i need to manually refresh it to make it work, i'm not sure what is causing it.

Very annoying 
Please Help!

![Untitled 1](https://user-images.githubusercontent.com/71181695/194704574-aebf9b1f-bcad-402a-8417-3419d130756e.jpg)

Thanks

**Comment by brianferguson** [comment]
>  When using with rainmeter 4.5.16 on windows 11, the "GPU Meter" won't auto refresh after restart or logoff and
i need to manually refresh it to make it work, i'm not sure what is causing it.

I have no idea what "GPU Meter" is, but I will assume it is part of some skin suite. Have you asked the author the skin for help?  If not (or you got no reply), your best bet is to ask for help with this skin on the [Rainmeter forums](https://forum.rainmeter.net/viewforum.php?f=5). Please include, at a minimum, the skin code in question (or a link to the skin suite).

Also, since that skin uses HWiNFO, make sure it is running and that your skin is configured correctly.

-Brian
