### ISSUE TITLE
How does Rainmeter keep windows from being minimized by Win+D?

### ISSUE THREAD

**Issue by kwyntes** [rainmeter/rainmeter#339]
I apologize in advance for misusing the Issues of this repository for my question, but I have no idea where to ask otherwise.

I would like to know how Rainmeter prevents its skin windows from being minimized when the user pressed the Win+D keys (to show the desktop). From what I found online (mostly Stackoverflow and MSDN Technet questions from ~2009), Win+D brings the desktop window to the front by altering some Z-index stuff, but I haven't been able to find out how exactly this works and, most importantly, how to workaround this/prevent this from happening.

I tried setting setting the parent of the window to the "progman" window, the desktop window, the shell window, all to no avail...
```c#
[DllImport("user32.dll", SetLastError = true)]
static extern IntPtr FindWindow(string lpClassName, string lpWindowName);

[DllImport("user32.dll")]
static extern IntPtr SetParent(IntPtr hWnd, IntPtr hParent);

[DllImport("user32.dll")]
static extern IntPtr GetDesktopWindow();
        
[DllImport("user32.dll")]
static extern IntPtr GetShellWindow();

// a)
SetParent(this.Handle, FindWindow("progman", "Program Manager"));
// b)
SetParent(this.Handle, GetDesktopWindow());
// c)
SetParent(this.Handle, GetShellWindow());
```

I also tried some stuff the internet kept suggesting with `SetWindowPos` like this:
```c#
[DllImport("user32.dll")]
static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int x, int y, int cx, int cy, uint uFlags);

SetWindowPos(Handle, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOSIZE | SWP_NOMOVE | SWP_NOACTIVATE);
```

... as well as overriding `WndProc` to prevent the window from getting minimized, and hooking into `WinEvent` to try to detect when the desktop window is brought to the front and placing the window on top again.  
I couldn't get any of it to work sadly...

**Comment by brianferguson** [comment]
There is no magical flag or winapi function that achieves this. The solution we came up with is to hook the `EVENT_SYSTEM_FOREGROUND` event, then manually set all the skins z-pos to above the desktop window. We also utilize a timer to periodically check the desktop state.

I won't get into the exact details (since that is beyond the scope of this issues section), but I will point you to the code that does this.

Here is the "hook": [System.cpp#L874-L906](https://github.com/rainmeter/rainmeter/blob/master/Library/System.cpp#L874-L906)

Here is the place where the z-pos changes: [System.cpp#L832-L868](https://github.com/rainmeter/rainmeter/blob/master/Library/System.cpp#L832-L868)

Here is the timer: [System.cpp#L933-L938](https://github.com/rainmeter/rainmeter/blob/master/Library/System.cpp#L933-L938)

You can follow the logic from there. You might want to research `WorkerW` windows as well. A lot of this was found by trial and error (and spy++) since MS hasn't really documented most of this.

Also, this was added way back in [2011](https://github.com/rainmeter/rainmeter/commit/8cb0a041e04a83151fc95fda4aa945fc90a306d0) and works most of the time. There are rare instances where the z-pos of a skin gets "out of order" and needs to be clicked on, but it's rare.

#

We also allow users to control this behavior with the [this](https://docs.rainmeter.net/manual/settings/rainmeter-section/#NormalStayDesktop) option, although I doubt anyone uses it.

-Brian
