### ISSUE TITLE
Please reduce your usage of nominatim.openstreetmap.org

### ISSUE THREAD

**Issue by lonvia** [rainmeter/rainmeter#367]
Rainmeter or one of its plugins (user agent "Rainmeter WebParser plugin") is using the geocoding services at nominatim.openstreetmap.org in a way that is starting to be disruptive. Our servers are being hit by requests from more than 4k Rainmeter clients precisely at the same time, three times per hour. The request always contain exactly the same search query. In other words, the code in questions asks every 20 Minutes where New York is.

Please change the code in question to be more server-friendly and make sure it is in line with our usage policy: responses should be cached and not repeated. Implementing caching will also bring your usage down to a permissible level. Where automated calls are used, make sure to add random jitter to spread out the requests over time between clients.

**Comment by brianferguson** [comment]
Unfortunately, this is a user's skin issue. While we can make a public request to skin authors to limit usage for your geocoding services, there is nothing "hard coded" on the Rainmeter end (or Webparser) to prevent this. Nor would we ever do so. It would be like asking google to limit requests coming from their chrome browser.

I have made an announcement to our users, you can see it here: [https://forum.rainmeter.net/viewtopic.php?t=43228](https://forum.rainmeter.net/viewtopic.php?t=43228)

Thank you for contacting us. Hopefully, skin authors will revise their code and make any necessary changes.

-Brian

**Comment by Drgabi18** [comment]
> Our servers are being hit by requests from more than 4k Rainmeter clients precisely at the same time, three times per hour. The request always contain exactly the same search query.

Not gonna lie, but this sounds like some **"genius"** most likely installed Rainmeter and a specific skin using GPO (Group Policies) in a data center in New York, as it's the only way to explain the big number of requests, and the time, since the computers open/deploy at the same time.

(I'm not affiliated with the project, I'm just an observer so everything below is just observations and stuff to make some info clear)

To add a bit on top of Brian's comment, there's nothing in Rainmeter hardcoded to specifically read your site, you can check the code and check how many downloads Rainmeter has using GitHub's API, if it were for anything to be hardcoded into Rainmeter, you wouldn't have 4K requests but [probably millions](https://api.github.com/repos/rainmeter/rainmeter/releases).

With Rainemter, users can create skins (basically widgets) that use measures (functions wrapped in a nice little package) for various stuff. The most logical (and only) use of your site in a Rainmeter project is for getting the lon/lat based off the search query a user inputted, which after that gets fed into another measure which gets the weather data.

https://forum.rainmeter.net/viewtopic.php?t=40899#p208170

You can check an example of such code here, somewhere in the skin the user inputs an address (like _Tartinijeva ul. 5_) or a city name (like _Salmiya_), and the site returns back that query, after the amount of time specified in `UpdateRate` passes (as a preventative measure by default 60 mins), the whole process happens again.

If there is someone to blame here, it would be the origin point of those 4K requests, for the standard user a request like this every 20 mins, although neither optimal or logical, shouldn't (maybe) be a problem, you never know if New York changes location. 

Skin authors will have to improve their code and understand that as part of using your/any API, they should be careful and understand that the actions they do affect the end. Seems like all the [skins on GitHub](https://github.com/search?q=nominatim.openstreetmap.org+rainmeter&type=code) that use your service are already optimized, so the feedback to the creators will have to be done on other platforms where they upload like DeviantArt.

**Comment by lonvia** [comment]
Thanks for getting the message out to your community. If the skin developers can fix their code in the way you mention, usage should be fine again.

That said, you do implement a service that allows skin developers to send regular automated requests to internet services. This is not the same as a manually operated web browser. So you really should think about save guards. I believe that there are at least two things you can and should do, to improve the situation:

* Amend the user agent you send to include information who is using the WebParser plugin (probably the name of the skin plus a version). This allows to ban badly configured skins on our side when necessary instead of banning the entire application.
* Enforce a random starting point for repeated requests, so that clients access the service at different times instead of having them all exactly asking at 10 minutes past the hour.

NB: the query string is not always New York, it was just an example. The queries come from all over the world. It's simply a very popular skin.

**Comment by Drgabi18** [comment]
> Amend the user agent you send to include information who is using the WebParser plugin (probably the name of the skin plus a version). This allows to ban badly configured skins on our side when necessary instead of banning the entire application.

This should be trivially easy and may go down one of two ways, either the skin authors
1. add `UserAgent="Rainmeter WebParser plugin - #CurrentConfig#"` into their skin
OOORRRR
2. the Rainmeter devs change [this line](https://github.com/rainmeter/rainmeter/blob/55b75a812f531aaf7510c66aef732a785a3e1302/Library/MeasureWebParser.cpp#L25) to `m_GlobalUserAgent((globalUserAgent && *globalUserAgent) ? globalUserAgent : (L"Rainmeter WebParser plugin" + L" - " + GetVariable(L"CURRENTCONFIG") )` when the next major release happens. This change will be invisible for the standard user and will only affect people who had the User Agent string literal in their caddyfile for whatever reason.

This won't stop the genius who `ForceReload`ed measures on some of their work, but will make it easier to track the specific people who we'll have to message.

**Comment by Lssg97** [comment]
> * Amend the user agent you send to include information who is using the WebParser plugin (probably the name of the skin plus a version). This allows to ban badly configured skins on our side when necessary instead of banning the entire application.

I personally think that it would be difficult to find the skin author who caused this effect, unless the skin author is still maintaining the skin. The solution I can think of is to block the IP addresses coming from these requests.

**Comment by Cariboudjan** [comment]
I did this.
