### ISSUE TITLE
Rainmeter probably interfering with GIMP due to invisible window

### ISSUE THREAD

**Issue by brunolopesdsilv** [rainmeter/rainmeter#374]
See: https://gitlab.gnome.org/GNOME/gimp/-/issues/1082

Seems that Rainmeter is interfering with GIMP due to some invisible window. Discussion would be appreciated at: https://gitlab.gnome.org/GNOME/gimp/-/issues/1742#note_633011

(Some question was made at IRC before but our bug tracker don't have this info.)

**Comment by brianferguson** [comment]
I cannot replicate the issue.

First, Rainmeter does not use the `WS_EX_NOACTIVATE | WS_EX_TRANSPARENT` combination window style (referenced in [#1082](https://gitlab.gnome.org/GNOME/gimp/-/issues/1082). The `WS_EX_TRANSPARENT` style is only used when a skins [clickthrough](https://docs.rainmeter.net/manual/settings/skin-sections/#ClickThrough) option is selected. This can be done by the skin itself (via the [!SetClickThrough](https://docs.rainmeter.net/manual/bangs/#ClickThrough) bang) or by the user selecting the appropriate settings (via [Manage](https://docs.rainmeter.net/manual/user-interface/manage/#SkinSettings) or the skins [context menu](https://docs.rainmeter.net/manual/user-interface/context-menus/#GeneralSettings)).

Reading through the various issues on gimp's gitlab, it seems like issue might be with how gtk tracks and/or handles mouse events - especially when dealing with differing image layers from within gimp.

Here is my attempt to replicate the video from issue [#1742](https://gitlab.gnome.org/GNOME/gimp/-/issues/1742#additional-information).

https://github.com/rainmeter/rainmeter/assets/1591640/17df0fd9-7e88-47b4-9d2a-11403bc000fd


Here is what I did:
1.  On a clean Windows 7 VM, I installed Gimp 2.10.36, Rainmeter 4.5.18 (and ShareX 15, for screen recording)
2. Opened an image with Gimp (then I minimized the window)
3. Started recording
4. Opened Rainmeter (standard illustro skins)
5. Restored the Gimp window
6. Performed similar "selection" (lasso and rectangle window) actions as the video from issue 1742
7. Minimized the Gimp window to show illustro "Welcome" skin
8. Changed 2 settings for the "Welcome" skin. First, "Stay topmost". This makes the skin appear on top of all windows. Second, "Clickthrough". This makes clicks on the skin pass through to the underlying window (in this case, Gimp). I even right clicked on the desktop and "Welcome" skin to show the desktop context menu (showing the click when "through" the skin to the desktop). I even right clicked on another skin to show the Rainmeter skin context menu.
9. Restored the Gimp window again, this time showing the Rainmeter "Welcome" skin on top of Gimp.
10. Performed the same "selection" actions as before, showing the selection appearing on the Gimp window instead of the Rainmeter window. The performance was the same as before the test.
11. I then performed some right clicks to show the Gimp context menu showing underneath the Rainmeter skin.

-Brian

PS - IRC details
<details>
  <summary>IRC logs</summary>


> (Some question was made at IRC before but our bug tracker don't have this info.)

Here is my chat logs on the question. Unfortunately, none of the dev team was around at the time and there was no response. :pensive:

``` txt
Oct 27 05:20:55 2019 *	schumaml (schumaml@nat/redhat/x-coquidujxtubywmr) has joined
Oct 27 05:22:26 2019 <schumaml>	hi, question about how rainmeter works in general - does it use fullscreen windows with WS_EX_NOACTIVATE | WS_EX_TRANSPARENT ?
Oct 27 05:23:21 2019 <schumaml>	it is interfering wit someone using GIMP, and applications using such windows - i.e. full-screen and transparent, e.g. to capture hotkeys or guestures - are known to do that.
Oct 27 05:23:55 2019 <schumaml>	issue is on the side of GTK, which considers windows to be fully covered in this case and discards events
```
</details>

**Comment by brunolopesdsilv** [comment]
> I cannot replicate the issue.
> 
> First, Rainmeter does not use the `WS_EX_NOACTIVATE | WS_EX_TRANSPARENT` combination window style (referenced in [#1082](https://gitlab.gnome.org/GNOME/gimp/-/issues/1082). The `WS_EX_TRANSPARENT` style is only used when a skins [clickthrough](https://docs.rainmeter.net/manual/settings/skin-sections/#ClickThrough) option is selected. This can be done by the skin itself (via the [!SetClickThrough](https://docs.rainmeter.net/manual/bangs/#ClickThrough) bang) or by the user selecting the appropriate settings (via [Manage](https://docs.rainmeter.net/manual/user-interface/manage/#SkinSettings) or the skins [context menu](https://docs.rainmeter.net/manual/user-interface/context-menus/#GeneralSettings)).
> 
> Reading through the various issues on gimp's gitlab, it seems like issue might be with how gtk tracks and/or handles mouse events - especially when dealing with differing image layers from within gimp.
> 
> Here is my attempt to replicate the video from issue [#1742](https://gitlab.gnome.org/GNOME/gimp/-/issues/1742#additional-information).
> 
>  Rainmeter_4.5.18-Gimp_2.10.36.mp4 
> Here is what I did:
> 
> 1. On a clean Windows 7 VM, I installed Gimp 2.10.36, Rainmeter 4.5.18 (and ShareX 15, for screen recording)
> 2. Opened an image with Gimp (then I minimized the window)
> 3. Started recording
> 4. Opened Rainmeter (standard illustro skins)
> 5. Restored the Gimp window
> 6. Performed similar "selection" (lasso and rectangle window) actions as the video from issue 1742
> 7. Minimized the Gimp window to show illustro "Welcome" skin
> 8. Changed 2 settings for the "Welcome" skin. First, "Stay topmost". This makes the skin appear on top of all windows. Second, "Clickthrough". This makes clicks on the skin pass through to the underlying window (in this case, Gimp). I even right clicked on the desktop and "Welcome" skin to show the desktop context menu (showing the click when "through" the skin to the desktop). I even right clicked on another skin to show the Rainmeter skin context menu.
> 9. Restored the Gimp window again, this time showing the Rainmeter "Welcome" skin on top of Gimp.
> 10. Performed the same "selection" actions as before, showing the selection appearing on the Gimp window instead of the Rainmeter window. The performance was the same as before the test.
> 11. I then performed some right clicks to show the Gimp context menu showing underneath the Rainmeter skin.
> 
> -Brian
> 
> PS - IRC details
> 
> IRC logs
> > (Some question was made at IRC before but our bug tracker don't have this info.)
> 
> Here is my chat logs on the question. Unfortunately, none of the dev team was around at the time and there was no response. 😔
> 
> ```
> Oct 27 05:20:55 2019 *	schumaml (schumaml@nat/redhat/x-coquidujxtubywmr) has joined
> Oct 27 05:22:26 2019 <schumaml>	hi, question about how rainmeter works in general - does it use fullscreen windows with WS_EX_NOACTIVATE | WS_EX_TRANSPARENT ?
> Oct 27 05:23:21 2019 <schumaml>	it is interfering wit someone using GIMP, and applications using such windows - i.e. full-screen and transparent, e.g. to capture hotkeys or guestures - are known to do that.
> Oct 27 05:23:55 2019 <schumaml>	issue is on the side of GTK, which considers windows to be fully covered in this case and discards events
> ```

Wow. Thank you very much by the extensive testing 🤗. Closing as not a bug.
