### ISSUE TITLE
RoundLine Meter with ControlAngle false

### ISSUE THREAD

**Issue by MathewOransky** [rainmeter/rainmeter#91]
If you have a RoundLine Meter with ControlAngle=0 the result will be... wrong.

In MeterRoundLine.cpp change line 129
from:
REAL sweepAngle = (REAL)(CONVERT_TO_DEGREES(m_RotationAngle * m_Value));
to:
REAL sweepAngle = (REAL)(CONVERT_TO_DEGREES(m_CntrlAngle ? m_RotationAngle * m_Value: m_RotationAngle));

Which allows the sweepAngle variable to be affected by the ControlAngle value. The result is circles are drawn instead of two polygons that are not circles for values <100%.

**Comment by brianferguson** [comment]
Unless I am misunderstanding the issue, the ControlAngle option is only meant to allow the value of the measure to control the angle at which the line is drawn (mainly if affects the staring and ending points of the line/arc). This shouldn't be used for the sweep angle. But there are other options that can affect the overall drawing, such as the Solid=1 option.

Changing this will have drastic effects on existing skins - and we make backwards compatibility our number 1 priority when possible.

If you would still like to explore a 'new' option for the Roundline meter that will draw the meter in a new and useful way, please feel free to make another pull request with the changes. A simple test skin showing the results and some pictures are also welcome. You can post those on the Rainmeter forums: https://forum.rainmeter.net/viewforum.php?f=14

-Brian

**Comment by MathewOransky** [comment]
Perhaps I poorly explained it. This is a problem when ControlAngle is Off/False/set to zero. The current effect is that even though control angle is off the sweepAngle is changing. This results in obvious graphics glitches. What should happens is that when ControlAngle is false then sweepAngle should remain constant; it should not change. It should remain the value of m_RotationAngle converted to Degrees. The change to MeterRoundLine.cpp that I proposed does not have side effects to other skins. I have used it and compiled it with no side effects. 

If need be I can present a simple example based on a loop measure that demonstrates the issue and validates the fix. A simple filled circle that should simply change diameter is currently not doing that because the sweepAngle is changing when it shouldn't be (because ControlAngle is set to zero).

**Comment by brianferguson** [comment]
> The change to MeterRoundLine.cpp that I proposed does not have side effects to other skins.

But it does have side effects. Your 'fix' totally changes how the meter is drawn. I simply used the example skin from our Roundline [documentation example](https://docs.rainmeter.net/manual-beta/meters/roundline/) (added ControlAngle=0 to both the Used and Free disk meters), and got different results with your version.
<br>

> This results in obvious graphics glitches.

I am not sure what 'glitches' you are seeing, but in the example referenced above (with `ControlAngle=0`), the arc simply 'closes' without drawing lines to the center of the circle. If `ControlAngle=1`, the arc draws lines from the start/end points of the arc to the center of the circle. Maybe it is possible that the 'glitches' you are seeing are small little arcs, or something else?
<br>

Since there is a difference in what is drawn from your version vs ours, we cannot accept your fix at this time. There are thousands of skins out there, and it is very likely that a change in the drawing behavior for this meter will break many skins. Again, backwards compatibility is our number one priority and this has a high chance of breaking that for many skins.


Also, like I said in my previous comment, we are willing to explore a 'new' option for the Roundline meter that can draw the meter in a different, more useful way - but the team will have to weigh the pros and cons to it before anything is decided. So there are no guarantees. Feel free to submit a pull request with the new option. As always, example skin code and pictures are helpful as well.

-Brian

PS - I am not sure what you are using RoundLine for, but perhaps the new Shape meter might help? https://docs.rainmeter.net/manual-beta/meters/shape/

**Comment by MathewOransky** [comment]
So that I could demonstrate the glitches I see in pictures I started this post.
https://forum.rainmeter.net/viewtopic.php?f=14&t=25148

If I am wrong and what I'm seeing is the desired behavior than I apologize for taking up your time, but I just don't see that setting ControlAngle=0 is actually stopping the RoundMeter widget from making Angle based changes.
